### ISSUE TITLE
Extention not working in Gnome 43

### ISSUE THREAD

**Issue by intra420** [Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-#1]
am not able to install the extension in Gnome 43 on Fedora 37
![image](https://user-images.githubusercontent.com/107241490/202318769-6b5b9c30-6a1a-49f6-b3a2-0a03a66a3a74.png)

**Comment by intra420** [comment]
created a pull request. just adding "43" into the metadata.json fixes it

**Comment by Hexcz** [comment]
Thanks for poiting that out, and i'm really sorry, i had some other things on my personal life to take care and forgot to update this. I also saw you've already updated the metadata file. Thanks for your help friendo.
