### ISSUE TITLE
Broken on gnome 44 -- easy fix!!

### ISSUE THREAD

**Issue by intra2** [Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-#3]
same fix that was done last time, simply add `, "44"` to the metadata.json

```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "When activating overview (Super button), the application view is shown instead of the view with the windows.",
  "name": "Start Overlay in Application View",
  "shell-version": [
    "40",
    "41",
    "42",
    "43",
    "44"
  ],
  "url": "https://github.com/Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-",
  "uuid": "start-overlay-in-application-view@Hex_cz",
  "version": 4
}
```
its working on my machine. no idea if more needs to be done or not.
also yaaaay gnome 44 and fedora 38 came out!!
I really like fedora 38's wall paper

**Comment by Hexcz** [comment]
Just adding 44 to metadata is enough since the functions used on this extension didn't changed. Thanks for your contribution and sorry for being late to update this, other stuff on my life are taking too much my time.
