### ISSUE TITLE
Not showing application menu

### ISSUE THREAD

**Issue by cedenoaugusto** [Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-#4]
I have installed Start-Overlay-in-Application-View on a notebook, but when I press super key nothing happend.

Distributor ID: Ubuntu 
Description: Ubuntu 22.04.2 LTS 
Release: 22.04 
Codename: jammy 
PREEMPT_DYNAMIC x86_64 
GNOME Shell 42.5

What could I check?

**Comment by Hexcz** [comment]
Hi Augusto, how are you doing? Interesting, i was on 42.5 and it was working flawlessly. I'm on 43.5 and it's still working. Could you tell me how did you installed? Via gnome-extensions, extensions app or cloning from repo? Thanks!

**Comment by cedenoaugusto** [comment]
Hello @Hexcz, thank you for your answer.

I have used gnome extentions to install it:
https://extensions.gnome.org/extension/5040/start-overlay-in-application-view/

Maybe I missed something.

Gnome extensions image:
![image](https://github.com/Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-/assets/3339822/a20b72db-80bc-4034-8454-d4d03bb9629d)

Extensions image:
![image](https://github.com/Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-/assets/3339822/c42d0930-5ece-4dde-964c-814f3a59aa36)



Regards

**Comment by Hexcz** [comment]
> Hello @Hexcz, thank you for your answer.
> 
> I have used gnome extensions to install it: https://extensions.gnome.org/extension/5040/start-overlay-in-application-view/
> 
> Maybe I missed something.
> 
> Gnome extensions image: ![image](https://user-images.githubusercontent.com/3339822/240042520-a20b72db-80bc-4034-8454-d4d03bb9629d.png)
> 
> Extensions image: ![image](https://user-images.githubusercontent.com/3339822/240042847-c42d0930-5ece-4dde-964c-814f3a59aa36.png)
> 
> Regards

Looks like everything is okay. Whats the behavior when you press super key? I suppose it's displaying the overview right? Could you try installing manualy please and see if the same thing happens? Thanks!

**Comment by cedenoaugusto** [comment]
Hi @Hexcz,

When I press super key, nothing happens. I have set overlay-key to blank, I mean, gsettings get org.gnome.mutter overlay-key = ''.

Files in cd start-overlay-in-application-view@Hex_cz
![image](https://github.com/Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-/assets/3339822/62b9769f-c378-43ba-afc7-bf26f25758f8)

Regards

**Comment by Hexcz** [comment]
> When I press super key, nothing happens. I have set overlay-key to blank, I mean, gsettings get org.gnome.mutter overlay-key = ''.


I see, this might be the culprit. Could you please uninstall the extension, then reset defaut settings for super key, then reinstall extension? Thanks for pointing that.

**Comment by Hexcz** [comment]
Glad to hear that. Thanks for pointing that issue, i might work on that on future.
