### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by IndrekHaav** [Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-#6]
Gnome 46 has been released, hopefully this extension can be updated to support it.

**Comment by Hexcz** [comment]
I'm still not using Gnome 46 atm, but i just did the metadata changes, could you please test it if you're on 46? Thx!

**Comment by IndrekHaav** [comment]
Seems to work fine (Arch Linux, Gnome 46).

**Comment by Hexcz** [comment]
Thanks for the feedback!
