### ISSUE TITLE
incompatible with gnome 46

### ISSUE THREAD

**Issue by rie39414** [Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-#8]
the extension is incompatible with gnome 46

**Comment by Hexcz** [comment]
Interesting, i tought i've updated for gnome 46. In fact, gnome 46 is listed on metadata. Could you confirm for me please the content of your local metadata file and the output of "gnome-shell --version" command? Ty.

**Comment by Hexcz** [comment]
Ah, it is possible that i've updated here but i forgot to update it on extensions.gnome.org :facepalm: . Did you install it from here or from extensions.gnome.org?

**Comment by Nanianmichaels** [comment]
Not OP, but I can confirm that I had mine installed from extensions.gnome.org and when updating to Fedora 40 it was disabled as incompatible.

When logging in this morning, I had the update announcement, and after the update I can confirm it works as expected.

Thank you for your work on this extension, it's one of the QoL ones I use on every machine I run GNOME on.

**Comment by Hexcz** [comment]
Great, thanks! After my 1st comment i noticed that i didnt updated extesions.gnome.org so i did it right away.
