### ISSUE TITLE
Add Gnome 47 Support

### ISSUE THREAD

**Issue by jemeckle** [Hexcz/Start-Overlay-in-Application-View-for-Gnome-40-#9]
Installing the extension from extensions.gnome.org shows incompatible with gnome 47.  I manually edited the metadata.json file on my computer and installed and can confirm everything works just fine (Ubuntu 24.10).  Love the extension!

**Comment by Hexcz** [comment]
Thx for the compliment mate! Sorry i couldn't update it yet (due to personal issues). I'll try to do it today.
